[workspace]

members = [
    "engine",
    "id",
    "cards",
    "events",
    "game_client",
    "game_runner",
    "websocket_console_client",
    "websocket_server",
    "tests",
    "webclient"
]